### ISSUE TITLE
插图

### ISSUE THREAD

**Issue by mangojuice123** [SmartKeyerror/Snorlax#1]
https://github.com/SmartKeyerror/Snorlax/tree/master/algorithm/backtracking
请问这个链接里的插图是用什么画出来的啊，感觉好好看 👍

**Comment by mangojuice123** [comment]
> 

![](https://github.com/SmartKeyerror/Snorlax/blob/master/algorithm/backtracking/images/search-string.png)
尤其是这张，真的很好看

**Comment by SmartKeyerror** [comment]
@mangojuice123 Hi~ 感谢对插图的好评，插图是使用 [draw.io](https://app.diagrams.net/) 这个在线绘图工具画的

**Comment by mangojuice123** [comment]
> @mangojuice123 Hi~ 感谢对插图的好评，插图是使用 [draw.io](https://app.diagrams.net/) 这个在线绘图工具画的

谢谢谢谢，我这就去试试看🐶
